Rails.application.routes.draw do
  get 'home/index'
  get 'home/marketplacedeactivesubpartner'

  get 'home/subscriberselect'
  get 'home/proapi'
  get 'home/apiplus'
  get 'home/informationsmsservice'

  get 'home/selectsubscriberdetail'
  get 'home/subscriberchangeprice'
  get 'home/deactivatesubscriber'
  get 'home/ccproxysaleform'
  get 'home/ccproxysale3dform'
  get 'home/wdticketsale3durlproxy'
  get 'home/wdticketsaleurlproxy'
  get 'home/marketplacewdticketmpsale'
  get 'home/marketplaceaddsubpartner'
  get 'home/marketplaceupdatesubpartner'
  get 'home/marketplaceaddsubpartnerOnlineVerify'
  get 'home/marketplaceupdatesubpartnerOnlineVerify'
  get 'home/marketplacesale3dsec'
  get 'home/marketplacempsale'
  get 'home/marketplacereleasepayment'
  get 'home/transactionrequestorder'
  get 'home/transactionrequestbympay'
  get 'home/tokenizeccurl'
  get 'home/tokenizecc'
  get 'home/success'
  get 'home/fail'

  post 'home/index'  
  post 'home/subscriberselect'  
  post 'home/proapi'  
  post 'home/apiplus'  
  post 'home/subscriberselect'  
  post 'home/subscriberchangeprice'
  post 'home/selectsubscriberdetail'  
  post 'home/deactivatesubscriber'  
  post 'home/ccproxysaleform'
  post 'home/ccproxysale3dform'
  post 'home/wdticketsaleurlproxy'
  post 'home/wdticketsale3durlproxy'
  post 'home/marketplaceaddsubpartner'
  post 'home/marketplaceupdatesubpartner'
  post 'home/marketplaceaddsubpartnerOnlineVerify'
  post 'home/marketplaceupdatesubpartnerOnlineVerify'
  post 'home/marketplacedeactivesubpartner'
  post 'home/marketplacesale3dsec'
  post 'home/marketplacempsale'
  post 'home/marketplacewdticketmpsale'
  post 'home/marketplacereleasepayment'
  post 'home/informationsmsservice'

  post 'home/transactionrequestorder'
  post 'home/transactionrequestbympay'
  post 'home/tokenizeccurl'
  post 'home/tokenizecc'
  post 'home/success'
  post 'home/fail'
  post 'home/tokenizesuccess'
  post 'home/tokenizefail'
  post 'home/successpost'
  post 'home/failpost'

  
  root 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end
